# Generated by Django 4.2.8 on 2024-05-21 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_category_alter_news_options_news_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-title'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-created_at'], 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
    ]
